// Calendário baseado no PNI — Programa Nacional de Imunizações (Ministério da Saúde).
// Cada vacina tem uma faixa etária (em meses) onde é recomendada.
// minMonths/maxMonths: faixa onde a vacina é aplicada (incluindo reforços).
// recurring: "annual" | null — indica se deve ser tomada repetidamente.

const VACCINES = [
  {
    id: "bcg",
    name: "BCG",
    description: "Protege contra formas graves de tuberculose. Dose única ao nascer.",
    minMonths: 0,
    maxMonths: 12 * 5,
    tags: ["Dose única", "Ao nascer"],
  },
  {
    id: "hepatite-b",
    name: "Hepatite B",
    description: "Protege contra o vírus da hepatite B. Primeira dose nas primeiras 24h de vida.",
    minMonths: 0,
    maxMonths: 12 * 99,
    tags: ["3 doses", "Toda a vida"],
  },
  {
    id: "pentavalente",
    name: "Pentavalente (DTP + Hib + Hep B)",
    description: "Difteria, tétano, coqueluche, Haemophilus influenzae B e hepatite B.",
    minMonths: 2,
    maxMonths: 7,
    tags: ["2, 4 e 6 meses"],
  },
  {
    id: "vip",
    name: "VIP (Poliomielite inativada)",
    description: "Protege contra a paralisia infantil. Doses aos 2, 4 e 6 meses.",
    minMonths: 2,
    maxMonths: 12,
    tags: ["2, 4 e 6 meses"],
  },
  {
    id: "pneumo-10",
    name: "Pneumocócica 10",
    description: "Protege contra infecções pneumocócicas (pneumonia, meningite, otite).",
    minMonths: 2,
    maxMonths: 12 * 5,
    tags: ["2 e 4 meses", "Reforço 12 meses"],
  },
  {
    id: "rotavirus",
    name: "Rotavírus",
    description: "Protege contra diarreias graves causadas pelo rotavírus.",
    minMonths: 2,
    maxMonths: 8,
    tags: ["2 e 4 meses"],
  },
  {
    id: "meningo-c",
    name: "Meningocócica C",
    description: "Protege contra meningite causada pelo meningococo C.",
    minMonths: 3,
    maxMonths: 12 * 11,
    tags: ["3 e 5 meses", "Reforço 12 meses"],
  },
  {
    id: "febre-amarela",
    name: "Febre Amarela",
    description: "Recomendada para áreas de risco. Primeira dose aos 9 meses.",
    minMonths: 9,
    maxMonths: 12 * 59,
    tags: ["9 meses", "Reforço aos 4 anos"],
  },
  {
    id: "triplice-viral",
    name: "Tríplice Viral",
    description: "Protege contra sarampo, caxumba e rubéola. Primeira dose aos 12 meses.",
    minMonths: 12,
    maxMonths: 12 * 59,
    tags: ["12 meses e 15 meses"],
  },
  {
    id: "hepatite-a",
    name: "Hepatite A",
    description: "Protege contra o vírus da hepatite A. Dose aos 15 meses.",
    minMonths: 15,
    maxMonths: 12 * 5,
    tags: ["15 meses"],
  },
  {
    id: "tetra-viral",
    name: "Tetra Viral / Varicela",
    description: "Sarampo, caxumba, rubéola e varicela (catapora).",
    minMonths: 15,
    maxMonths: 12 * 4 + 11,
    tags: ["15 meses", "Reforço aos 4 anos"],
  },
  {
    id: "dtp-reforco",
    name: "DTP (Reforço infantil)",
    description: "Reforço da tríplice bacteriana: difteria, tétano e coqueluche.",
    minMonths: 15,
    maxMonths: 12 * 7,
    tags: ["15 meses e 4 anos"],
  },
  {
    id: "hpv",
    name: "HPV",
    description: "Previne o papilomavírus humano, causador do câncer de colo do útero e outros.",
    minMonths: 12 * 9,
    maxMonths: 12 * 45,
    tags: ["9 a 14 anos", "2 doses"],
  },
  {
    id: "meningo-acwy",
    name: "Meningocócica ACWY",
    description: "Protege contra múltiplos tipos de meningococo. Recomendada para adolescentes.",
    minMonths: 12 * 11,
    maxMonths: 12 * 14 + 11,
    tags: ["11 a 14 anos"],
  },
  {
    id: "dt",
    name: "dT (Dupla Adulto)",
    description: "Difteria e tétano. Reforço a cada 10 anos durante toda a vida adulta.",
    minMonths: 12 * 7,
    maxMonths: 12 * 120,
    tags: ["Reforço a cada 10 anos"],
  },
  {
    id: "influenza",
    name: "Influenza (Gripe)",
    description: "Vacinação anual, prioritária para crianças, idosos, gestantes e grupos de risco.",
    minMonths: 6,
    maxMonths: 12 * 120,
    tags: ["Anual"],
    recurring: "annual",
  },
  {
    id: "covid",
    name: "COVID-19",
    description: "Recomendada conforme orientação vigente do Ministério da Saúde.",
    minMonths: 6,
    maxMonths: 12 * 120,
    tags: ["Segundo campanha vigente"],
  },
  {
    id: "pneumo-23",
    name: "Pneumocócica 23",
    description: "Recomendada para idosos acima de 60 anos institucionalizados e grupos de risco.",
    minMonths: 12 * 60,
    maxMonths: 12 * 120,
    tags: ["60+", "Grupos de risco"],
  },
  {
    id: "herpes-zoster",
    name: "Herpes Zóster",
    description: "Previne o herpes zóster (cobreiro). Recomendada a partir dos 50 anos.",
    minMonths: 12 * 50,
    maxMonths: 12 * 120,
    tags: ["50+"],
  },
  // Condicionais
  {
    id: "dtpa",
    name: "dTpa (Gestante)",
    description: "Protege o recém-nascido contra coqueluche. Aplicada a cada gestação, a partir da 20ª semana.",
    condition: "pregnant",
    tags: ["Gestação", "A partir da 20ª semana"],
  },
];

// Faixas etárias do calendário completo
const CALENDAR_GROUPS = [
  {
    title: "Ao nascer",
    age: "0 meses",
    vaccines: ["BCG", "Hepatite B (1ª dose)"],
  },
  {
    title: "2 meses",
    age: "2 meses",
    vaccines: ["Pentavalente", "VIP", "Pneumocócica 10", "Rotavírus"],
  },
  {
    title: "3 meses",
    age: "3 meses",
    vaccines: ["Meningocócica C"],
  },
  {
    title: "4 meses",
    age: "4 meses",
    vaccines: ["Pentavalente", "VIP", "Pneumocócica 10", "Rotavírus"],
  },
  {
    title: "5 meses",
    age: "5 meses",
    vaccines: ["Meningocócica C"],
  },
  {
    title: "6 meses",
    age: "6 meses",
    vaccines: ["Pentavalente", "VIP", "Influenza (anual)"],
  },
  {
    title: "9 meses",
    age: "9 meses",
    vaccines: ["Febre Amarela"],
  },
  {
    title: "12 meses",
    age: "12 meses",
    vaccines: ["Tríplice Viral", "Pneumo 10 (reforço)", "Meningo C (reforço)"],
  },
  {
    title: "15 meses",
    age: "15 meses",
    vaccines: ["DTP", "VOP", "Hepatite A", "Tetra Viral"],
  },
  {
    title: "4 anos",
    age: "4 anos",
    vaccines: ["DTP (reforço)", "VOP", "Varicela", "Febre Amarela (reforço)"],
  },
  {
    title: "Adolescente",
    age: "9 a 14 anos",
    vaccines: ["HPV", "Meningocócica ACWY", "dT", "Hepatite B"],
  },
  {
    title: "Adulto",
    age: "20 a 59 anos",
    vaccines: ["dT (10 em 10 anos)", "Tríplice Viral", "Hepatite B", "Febre Amarela", "Influenza"],
  },
  {
    title: "Idoso",
    age: "60 anos ou mais",
    vaccines: ["Influenza (anual)", "Pneumocócica 23", "dT", "Herpes Zóster", "Febre Amarela"],
  },
  {
    title: "Gestante",
    age: "Durante a gestação",
    vaccines: ["dTpa", "Hepatite B", "Influenza"],
  },
];
